### ISSUE TITLE
Upload build Linux gcc 6.1.1 libstdc++11

### ISSUE THREAD

**Issue by uilianries** [lasote/conan-poco#4]
Hi!

I'm using gcc 6.1 and libstdc++11 for my builds, however, this receipt is not official in the repository.

I used the follow command to build:

> conan install Poco/1.7.3@lasote/stable -s compiler=gcc -s compiler.version=6.1 -s compiler.libcxx=libstdc++11 --build=missing

Works fine! I'm using a Docker container to build: [here](https://hub.docker.com/r/uilianries/docker-conan/builds/bnbv8vj9euwhpqj5meqbbfe/)

How can I upload binary package? I did not modify conanfile.py from Poco@lasote.

Regards.

**Comment by lasote** [comment]
HI!

We usually don't accept "binary" contributions to our channels because it can be a little risky.
You can fork the recipe, export to your **user/channel** and upload them to your namespace.
You can also use the "conan copy" command to change the user/channel of your local packages and then upload to your namespace.

I've pending to update the conan package tools repository to allow auto building with gcc 6.1, I'm sure your conanfile will be useful!

Thanks

**Comment by uilianries** [comment]
Thanks for the answer,

Okay, I will export the forked recipe on my channel. I believe that the new recipe (gcc 6.1 support) will be helpful.

Regards.
